name: Run Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        pip install -r requirements/dev
     
    - name: Launch tests
      run: |
        pytest --cov=checkQC tests/

    - name: Update stats to CodeCov
      uses: codecov/codecov-action@v3
